export const warning  = {
    internalError: "Erro interno do servidor.",
    noUserId: "Usuario não encontrado.",
    userAddSucess: "Usuario criado com sucesso",
    userDeleted: "Usuario deletado com sucesso.",
    userUpdated: "Usuario atualizado com sucesso.",
    noUsers: "Nenhum usuario cadastrado.",
    mailIncorrect: "Formato de email invalido.",
    noNumberName: "Nome não pode conter apenas números.",
    noNumberSurname: "Sobrenome não pode conter apenas números.",
    emptyName: "Nome não pode ser vázio",
    emptySurname: "Sobrenome não pode ser vázio",
    nameLenght: "Tamanho do nome incorreto",
    surnameLenght: "Tamanho do sobrenome incorreto",
    invalidPhone: "Informe um telefone válido.",
    invalidDate: "Informe uma data válida",
    routeNotFound: "Rota não encontrada",
    invalidStatus: "Revise o status do usuario",
    passwordFormat: "Senha não corresponde ao formato exigido",
    emailInUse: "Esse email não está disponivel.",
    unauthorized: "Não autorizado.",
    welcome: "Autenticado com sucesso!"
}